time= input("please enter a number from 1 to 12: ")
items= input('please enter a noun(plural): ')
name= input("please enter a name: ")
# capitalized_name = name.capitalize()
scream= input("please enter any sentence: ")
# uppercase_scream = scream.upper()
action = input("please enter a verb: ")
print ()
print ()
print ()
print ("Mad libs where libs get Mad\n Start Below:") 
print ()
print () 
print ("Number: " + time) 
print ("Noun(plural): " + items)
print ("Name: " + name.capitalize())
print ("Any sentence: " + scream.upper())
print ("Verb: " + action)
print ()
print ()
print("\tIt was %s o'clock when I hears a knock at the door." %(time))
# to get a tab (or four spaces) we use \t
print("\tI opened the door and there was a box full of %s with a note saying 'From Mr. %s.'" %(items, name.capitalize()))
print("\tJust as I closed the door I heard a scream '%s.'" %(scream.upper()))
print("\tI froze in place and all I could do was %s." %(action))
